package net.xicp.zyl_me.dal.entity;

// Generated 2015-7-20 14:51:46 by Hibernate Tools 4.3.1
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.PropertySource;

/**
 * MessageBoard generated by hbm2java
 */
@Entity
@Table(name = "message_board", catalog = "zyl_me")
public class MessageBoard implements java.io.Serializable {
	private Integer id;
	private String email;
	private String name;
	private String content;
	private Date time;

	public MessageBoard() {
	}

	public MessageBoard(String name, String content, Date time) {
		this.name = name;
		this.content = content;
		this.time = time;
	}

	public MessageBoard(String email, String name, String content, Date time) {
		this.email = email;
		this.name = name;
		this.content = content;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "content", length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "time", length = 10)
	public Date getTime() {
		return this.time;
	}

	@Override
	public String toString() {
		return "MessageBoard [id=" + id + ", email=" + email + ", name=" + name + ", content=" + content + ", time=" + time + "]";
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Override
	public boolean equals(Object obj) {
		MessageBoard msgboard = (MessageBoard)obj;
		return this.name.equals(msgboard.name) && this.content.equals(msgboard.content);
	}
}
